[package]
name = "agendao-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
agendao-multimodal = { path = "../agendao-multimodal" }
agendao-skill = { path = "../agendao-skill" }
agendao-types = { path = "../agendao-types" }
agendao-orchestrator = { path = "../agendao-orchestrator" }
serde = { workspace = true }
serde_json = { workspace = true }
