//! 金 — Unified dialog layer authority.

pub mod backdrop;
pub mod help;
pub mod permission;
pub mod question;
pub mod agent_select;
pub mod clipboard;
pub mod confirm;
pub mod mode_select;
pub mod model_select;
pub mod prompt_stash;
pub mod session_export;
pub mod session_fork;
pub mod session_list;
pub mod session_rename;
pub mod skill_list;
pub mod skill_proposal;
pub mod mcp_list;
pub mod recovery_list;
pub mod task_list;
pub mod model_edit;
pub mod mcp_edit;
pub mod plugin_edit;
pub mod provider_edit;

pub use confirm::ConfirmDialog;
pub use help::HelpDialog;
pub use permission::{PermissionDialog, PermissionReply, PermissionRequest, PermissionType, PermissionLifetime};
pub use question::{QuestionDialog, QuestionRequest, QuestionOption};
pub use agent_select::{AgentSelectDialog, AgentEntry};
pub use prompt_stash::{StashDialog, StashEntry};
pub use mode_select::{ModeSelectDialog, ModeEntry};
pub use model_select::{ModelSelectDialog, ModelEntry, ModelDialogOutcome, ProviderGroup};
pub use session_export::{ExportAction, SessionExportDialog};
pub use session_fork::{SessionForkDialog, ForkMessageOption};
pub use session_list::{SessionListDialog, SessionEntry, SessionListAction};
pub use session_rename::SessionRenameDialog;
pub use skill_list::{SkillListDialog, SkillEntry, SkillListAction};
pub use skill_proposal::{SkillProposalDialog, SkillProposalEntry, SkillProposalAction};
pub use mcp_list::{McpListDialog, McpEntry, McpAction};
pub use recovery_list::{RecoveryListDialog, RecoveryEntry, RecoveryAction};
pub use task_list::{TaskListDialog, TaskEntry, TaskAction};
pub use model_edit::{ModelEditDialog, ModelEditAction, ModelEditSubmission, ModelEditMode};
pub use mcp_edit::{McpEditDialog, McpEditAction, McpEditSubmission, McpEditMode, McpTransport};
pub use plugin_edit::{PluginEditDialog, PluginEditAction, PluginEditSubmission};
pub use provider_edit::{ProviderEditDialog, ProviderEditAction};
pub(crate) use provider_edit::ProviderEditField;
