[package]
name = "agendao-skill"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
agendao-config = { path = "../agendao-config" }
agendao-types = { path = "../agendao-types" }
agendao-util = { path = "../agendao-util" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
thiserror = { workspace = true }
tracing = { workspace = true }
walkdir = "2"
dirs = { workspace = true }
sha2 = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "charset", "http2", "system-proxy"] }
flate2 = "1"
which = "7"

[dev-dependencies]
tempfile = "3"
